### ISSUE TITLE
Create a progress bar to report the number of Spark tasks remaining while executing a cell.

### ISSUE THREAD

**Issue by vitillo** [mreid-moz/jupyter-spark#3]
Ideally we would like to have the same functionality that [Zeppelin](https://zeppelin.incubator.apache.org/) notebooks provide to monitor the duration of a cell.

**Comment by musicaljelly** [comment]
James already has a variant of this working in his keyboard_shortcut branch. The progress of any active spark jobs are shown in the dialogue that appears when you hit alt+s (although it doesn't yet always update in real time).

Does this task involve a separate progress bar that is displayed, say, right underneath the cell the moment you run it? Or has James's implementation already covered this task?

**Comment by vitillo** [comment]
Glad to hear there was some progress :+1:  This task involves a separate progress bar underneath the cell though.

**Comment by shaybeau731** [comment]
I'll start working on adding a progress bar UI element that appears below a cell when it's executing Spark tasks. Later I'll work on getting it to update as the Spark tasks complete (or somebody else can work on that now, if they want).

**Comment by musicaljelly** [comment]
Sounds good. I'll pick up a different task if there's something that hasn't been added to github yet.

**Comment by yeah568** [comment]
@shaybeau731 I just updated my branch with some code that adds a local cache, that can be shared, and gets auto-updated every 10 seconds. You can use the cache if you want, at the very least it'll save on GET requests to the API.

**Comment by shaybeau731** [comment]
Excellent, thanks @yeah568! I'll merge it in with my branch.

**Comment by mreid-moz** [comment]
#11 addresses this issue
